import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { CartProvider } from "@/context/CartContext";
import ScrollToTop from "./components/ScrollToTop";
import WhatsAppButton from "./components/WhatsAppButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">

      <body className="min-h-full flex flex-col">
        <CartProvider>
        <Header />
        {children}
         <Footer />

         <ScrollToTop />
         <WhatsAppButton />
         </CartProvider>
        </body>
    </html>
  );
}
